### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by RothAndrew** [ttu-capstone-podman/podman-installer-mac#6]
Story:
As a developer of the podman-installer-mac, I want each pull request to be automatically tested

Acceptance Criteria:
1. Each Pull Request is automatically tested
1. The pull request is not allowed to be merged if the test(s) fail

Notes:

1. Go to the Marketplace tab > Continuous Integration category. Pick one or two apps that do automated code quality or other checks, that have free tiers for open source projects. Set them up and test that they work.
1. @RothAndrew added Hound already, make sure it works.

**Comment by jonespaul327** [comment]
Below is an image showing I got Codacy to work along with Hound.

![image](https://user-images.githubusercontent.com/56886605/67860234-50b7eb80-faeb-11e9-9824-78c997519b99.png)

**Comment by RothAndrew** [comment]
@jonespaul327 please pick 2 people to peer review your work with you.

Reviewers: Please review with Paul. Make sure each acceptance criteria is met. If Paul gets 2 approvals, move this task to the done column.

**Comment by jonespaul327** [comment]
Codacy is no longer responding. I am moving it back to "In Progress."
