### ISSUE TITLE
SPIKE: Investigate MacinCloud

### ISSUE THREAD

**Issue by RothAndrew** [ttu-capstone-podman/podman-installer-mac#7]
Story:
In order to complete our project successfully, each developer needs access to a MacOS environment. [MacinCloud](https://www.macincloud.com/) needs to be evaluated as a possible candidate to accomplish this.

ACs:
- I can perform work with minimal roadblocks compared to having a physical Macbook
- My environment is saved between sessions
- I have admin/sudo access
- I am allowed to install whatever I want
- Is capable of running a linux VM

Notes:
- MacinCloud looks to be a cloud service that offers cloud workstations of MacOS
- This is a [spike](https://www.leadingagile.com/2016/09/whats-a-spike-who-should-enter-it-how-to-word-it/). Spend as little time on it as possible trying to prove or disprove each of the ACs.
- It is a paid service, so involvement with school officials to figure out how it gets paid for will be needed.

**Comment by RothAndrew** [comment]
@jdevans43 I'm going to reword the story a little bit to make it look more like a [spike](https://www.leadingagile.com/2016/09/whats-a-spike-who-should-enter-it-how-to-word-it/). Acceptance criteria shouldn't change.

**Comment by RothAndrew** [comment]
Adding another acceptance criteria that may be difficult to prove/disprove right away, but we need to know if it is possible:

- Is capable of running a linux VM

**Comment by tmburks42** [comment]
I've reached out to MacinCloud, they can enable virtualization with the dedicated server plan.
