### ISSUE TITLE
SPIKE: Investigate other Cloud MacOS workstation options

### ISSUE THREAD

**Issue by AaronOtto11** [ttu-capstone-podman/podman-installer-mac#9]
Story:
In order to facilitate each developer having a MacOS environment to work in, we need to investigate what other options are available to run a cloud MacOS workstation, in case MacinCloud doesn't pan out.

Acceptance Criteria:
1. Does not require locked in contract (month-to-month)
1. Pricing is reasonable
1. List of alternatives is present in this issue as a comment.

Notes:
- This is a spike. Spend as little time as necessary to complete the acceptance criteria
- Just compile the list, don't evaluate each one. Separate spike stories will be created to do that.

**Comment by tmburks42** [comment]
Other options we looked at: XCodeClub and VirtualMacosx.com. XCodeClub is run by a single person and we have doubts about the availability for support and the reliability of the site. VirtualMacosx.com has plans that offer root access, but we can't find much documentation about the service, and there are not many reviews for the site.
